Increase memory available to webpacker
We were getting following error unless increasing memory
available to Node:

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x8c21ec [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
 6: 0xd4b133 [node]
 7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 8: 0x66f38042fd
Aborted (core dumped)
```

Reverting previous approach with WEBPACK_BIN because setting
NODE_OPTIONS seems to resolve the issue as well and is more
readable.

Signed-off-by: Miha Pleško <miha.plesko@xlab.si>