Topology screens - fix parseUrl to deal with hash router
Since https://github.com/ManageIQ/manageiq-ui-classic/pull/4284,
our urls can end with a hash + a route.

But the topology "where am I" url parsing code failed to take that into account, resulting in gets for undefined urls:

    angular.self-f52e96200e93eab5e5989b1cfc1563dcd14957ec50245b37ea763e6abd127a54.js:14962 Error: [$http:badreq] Http request configuration url must be a string or a $sce trusted object.  Received: undefined
    https://errors.angularjs.org/1.6.10/$http/badreq?p0=undefined
        at angular.self-f52e96200e93eab5e5989b1cfc1563dcd14957ec50245b37ea763e6abd127a54.js:126
        at $http (angular.self-f52e96200e93eab5e5989b1cfc1563dcd14957ec50245b37ea763e6abd127a54.js:12345)
        at Function.$http.(anonymous function) [as get] (http://localhost:3000/assets/angular/angular.self-f52e96200e93eab5e5989b1cfc1563dcd14957ec50245b37ea763e6abd127a54.js?body=1:12626:18)
        at NetworkTopologyCtrl.controller.refresh (topology_service.self-c603c946f63ec7a10e96c995629c8421ebdce0c741ab4f07065db80c7cdb9c8e.js:287)
        at Object.mixinTopology (topology_service.self-c603c946f63ec7a10e96c995629c8421ebdce0c741ab4f07065db80c7cdb9c8e.js:326)
        at NetworkTopologyCtrl (network_topology_controller.self-066c5e882e6e89f073cc47542bc7827285fb13d00dc65516ac1bfac5a07f4cc9.js:10)
        at Object.invoke (angular.self-f52e96200e93eab5e5989b1cfc1563dcd14957ec50245b37ea763e6abd127a54.js:5118)
        at $controllerInit (angular.self-f52e96200e93eab5e5989b1cfc1563dcd14957ec50245b37ea763e6abd127a54.js:11140)
        at nodeLinkFn (angular.self-f52e96200e93eab5e5989b1cfc1563dcd14957ec50245b37ea763e6abd127a54.js:10003)
        at compositeLinkFn (angular.self-f52e96200e93eab5e5989b1cfc1563dcd14957ec50245b37ea763e6abd127a54.js:9312)